services:
  app:
    restart: always
    build: .
    command: "sh app-entry-point.sh"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - celery
    volumes:
      - "./media:/app/media"
  celery:
    restart: always
    build: .
    command: celery -A main worker -l info
    depends_on:
      - redis
    volumes:
      - "./media:/app/media"
  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - "./database:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
