# Generated by Django 4.2.4 on 2023-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=51, unique=True, verbose_name="Название магазина"),
                ),
                (
                    "price_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="prices",
                        verbose_name="Прайс файл магазина",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[
                            (True, "Готов принимать заказы"),
                            (False, "Не готов принимать заказы"),
                        ],
                        default=False,
                        verbose_name="Статус магазина",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="Email магазина"),
                ),
                (
                    "phone",
                    models.CharField(max_length=21, unique=True, verbose_name="Телефон магазина"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
    ]
