# Generated by Django 4.2.4 on 2023-08-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_shopmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserManagerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shops",
                    models.ManyToManyField(
                        related_name="managers",
                        to="backend.shopmodel",
                        verbose_name="Магазины",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
            },
        ),
    ]
