# Generated by Django 4.2.4 on 2023-08-13 15:09

from django.db import migrations, models

import backend.models.shop_models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_rename_productparameter_productparametermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopmodel",
            name="price_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.shop_models.update_filename,
                verbose_name="Прайс файл магазина",
            ),
        ),
    ]
