# Generated by Django 4.2.4 on 2023-08-19 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_orderaddressmodel_ordermodel_orderitemmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
