# Generated by Django 4.2.4 on 2023-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_ordermodel_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItemModel",
            new_name="OrderPositionModel",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="additional",
            field=models.TextField(blank=True, null=True, verbose_name="Дополнительная информация"),
        ),
    ]
