# Generated by Django 4.2.4 on 2023-08-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_rename_orderitemmodel_orderpositionmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpositionmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_positions",
                to="backend.ordermodel",
                verbose_name="Заказ",
            ),
        ),
    ]
