# Generated by Django 4.2.4 on 2023-08-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_orderpositionmodel_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество товара"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена товара")),
                (
                    "price_rrc",
                    models.PositiveIntegerField(verbose_name="Рекомендованная розничная цена"),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
            },
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="backend.orderaddressmodel",
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.DeleteModel(
            name="OrderPositionModel",
        ),
        migrations.AddField(
            model_name="orderitemsmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="backend.ordermodel",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="orderitemsmodel",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="backend.productshopmodel",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitemsmodel",
            unique_together={("order", "position")},
        ),
    ]
