# Generated by Django 4.2.4 on 2023-08-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_orderitemsmodel_alter_ordermodel_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemsmodel",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="backend.productshopmodel",
                verbose_name="Товар",
            ),
        ),
    ]
