# Generated by Django 4.2.4 on 2023-08-22 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_orderitemsmodel_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemsmodel",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="backend.productshopmodel",
                verbose_name="Позиция",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemsmodel",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="orderitemsmodel",
            name="price_rrc",
            field=models.PositiveIntegerField(verbose_name="РРЦ"),
        ),
        migrations.AlterField(
            model_name="orderitemsmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="categories",
            field=models.ManyToManyField(
                related_name="products",
                to="backend.categorymodel",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productshopmodel",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="productshopmodel",
            name="price_rrc",
            field=models.PositiveIntegerField(verbose_name="РРЦ"),
        ),
        migrations.AlterField(
            model_name="productshopmodel",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
        migrations.CreateModel(
            name="PasswordResetTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="Токен"
                    ),
                ),
                (
                    "expire",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 8, 27, 15, 44, 39, 268094),
                        editable=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
