# Generated by Django 4.2.4 on 2023-08-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_rename_orderitemsmodel_orderitemmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametermodel",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название параметра"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 15, 25, 34, 744369),
                verbose_name="Истекает",
            ),
        ),
    ]
