# Generated by Django 4.2.4 on 2023-08-29 12:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_alter_parametermodel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametermodel",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Название параметра"),
        ),
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 15, 26, 23, 365912),
                verbose_name="Истекает",
            ),
        ),
        migrations.AlterField(
            model_name="productparametermodel",
            name="value",
            field=models.TextField(verbose_name="Значение параметра"),
        ),
    ]
