# Generated by Django 4.2.4 on 2023-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_alter_parametermodel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Истекает"
            ),
        ),
    ]
