# Generated by Django 4.2.4 on 2023-08-29 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_alter_parametermodel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 16, 49, 59, 13659),
                verbose_name="Истекает",
            ),
        ),
    ]
