# Generated by Django 4.2.4 on 2023-08-29 13:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_alter_passwordresettokenmodel_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 16, 59, 19, 221979),
                verbose_name="Истекает",
            ),
        ),
    ]
