# Generated by Django 4.2.4 on 2023-10-18 13:11

import backend.utils.user_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_alter_passwordresettokenmodel_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expire",
            field=models.DateTimeField(
                default=backend.utils.user_utils.generate_token_expire_time,
                verbose_name="Истекает",
            ),
        ),
    ]
